apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: docs
data:
  nginx.conf: |-
    user nginx;
    worker_processes  8;

    events {
      worker_connections  512;
    }

    http {
      keepalive_timeout   65;

      server {
        listen 80;
        server_name docs.mekstack.ru;

        location / {
          resolver kube-dns.kube-system.svc.cluster.local ipv6=off;
          set $bucket "mekstack-docs.website.yandexcloud.net";
          proxy_intercept_errors on;
          proxy_redirect off;
          proxy_set_header Host $bucket;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://$bucket/master$request_uri;
        }

        location /healthz {
          access_log off;
          add_header 'Content-Type' 'application/json';
          return 200 '{"status":"UP"}';
        }
      }

      server {
        listen 80;
        server_name "~^pr-(?<branch>\d{1,3})\.docs\.staging\.mekstack\.ru$";

        location / {
          resolver kube-dns.kube-system.svc.cluster.local ipv6=off;
          set $bucket "mekstack-docs.website.yandexcloud.net";
          proxy_intercept_errors on;
          proxy_redirect off;
          proxy_set_header Host $bucket;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://$bucket/pr-$branch$request_uri;
        }
      }
    }
