apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: docs
data:
  nginx.conf: |-
    user nginx;
    worker_processes  1;

    events {
      worker_connections  512;
    }

    http {
      include      mime.types;
      default_type application/octet-stream;

      keepalive_timeout   65;
      types_hash_max_size 4096;

      server {
        listen 80;

        location / {
          root /html;
          index index.html;
        }

        location /healthz {
            access_log off;
            add_header 'Content-Type' 'application/json';
            return 200 '{"status":"UP"}';
        }
      }
    }
