heat_template_version: wallaby

parameter_groups:
  - label: Basic Configuration
    description: Basic resource and network settings
    parameters:
      - instance_description
      - network_cidr
      - instance_image
      - instance_type
      - volume_size
      - public_key

parameters:
  network_cidr:
    default: '192.168.0.0/24'
    type: string
    label: Сеть
    description: CIDR для подсети

  instance_image:
    type: string
    label: Операционная Система
    constraints:
      - allowed_values:
          - Ubuntu 22.04.3 LTS
          - Arch Linux

  public_key:
    type: string
    label: Публичный Ключ SSH
    description: |
      Ключ, по которому заходить в виртуалочку.
      Начинается на ssh-rsa AAAAA...

  instance_type:
    type: string
    label: Размер
    constraints:
      - allowed_values:
          - 4 vCPU, 512MB RAM
          - 6 vCPU, 1GB RAM
          - 8 vCPU, 4GB RAM
          - 6 vCPU, 2GB RAM

  volume_size:
    type: number
    label: Диск, GB
    description: Размер диска для виртуалки
    default: 10

  instance_description:
    type: string
    label: Описание
    description: Для чего виртуалка?

resources:
  private_network:
    type: OS::Neutron::Net
    properties:
      name: { get_param: "OS::stack_name" }

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: private_network }
      cidr: { get_param: network_cidr }

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: public
      name: { get_param: "OS::stack_name" }

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet: { get_resource: private_subnet }

  secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name: { get_param: "OS::stack_name" }
      rules:
        - protocol: icmp
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - protocol: tcp
          port_range_min: 443
          port_range_max: 443

  cinder_volume:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: volume_size }

  instance_keypair:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: "OS::stack_name" }
      public_key: { get_param: public_key }

  instance:
    type: OS::Nova::Server
    properties:
      name: { get_param: "OS::stack_name" }
      image: { get_param: instance_image }
      flavor:
        # TODO string_replace / map to real flavors
      key_name: { get_resource: instance_keypair }
      networks:
        - network: { get_resource: private_network }
      security_groups:
        - { get_resource: secgroup }
      block_device_mapping:
        - device_name: vda
          volume_id: { get_resource: cinder_volume }
      metadata:
        description: { get_param: instance_description }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public

  associate_floating_ip:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_attr: [instance, first_address] }

outputs:
  instance_floating_ip:
    label: Floating IP
    description: IP виртуалочки
    value: { get_attr: [floating_ip, floating_ip_address] }
