name: Bump Deployment Timestamp

on:
  push:
    branches:
      - master
    paths:
      - '**.rst'

jobs:
  update-timestamp:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Update Deployment Timestamp
      run: |
        DATE_STR=$(date -u +"%d %b %H:%M")
        sed -i '/last-updated:/c\ \ \ \ last-updated: "'"$DATE_STR"'"' ./manifests/docs.yaml

    - name: Commit and Push Changes
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Actions"
        git add ./mainfests/docs.yaml
        git commit -m "chore(k8s): bump timestamp for fleet" || echo "No changes to commit"
        git push
